language: node_js
node_js:
  - 8

cache:
  directories:
  - node_modules
  - functions/node_modules

before_install:
  - chmod +x before_install.sh
  - ./before_install.sh


before_script:
  - npm test
  - chmod +x build.sh
  - travis_wait 40 ./build.sh

script:
  - chmod +x deploy.sh
  - travis_wait 40 ./deploy.sh


  
